name: Deploy to Aliyun ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/finall_lab:latest
      
      - name: SSH and deploy on Aliyun ECS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ecs-user  # 阿里云ECS默认用户名
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            # 创建项目目录
            mkdir -p ~/finall_lab
            cd ~/finall_lab
            
            # 从GitHub获取最新配置
            curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml -o docker-compose.yml
            
            # 替换为使用Docker Hub镜像
            sed -i 's/build: \./image: ${{ secrets.DOCKER_HUB_USERNAME }}\/finall_lab:latest/g' docker-compose.yml
            
            # 检查并安装docker-compose（如果需要）
            if ! command -v docker-compose &> /dev/null; then
              echo "安装docker-compose..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # 部署应用
            docker-compose down || true
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker ps -a